### ISSUE TITLE
Extend Light Theme to Entire Site

### ISSUE THREAD

**Issue by ghost** [9inevolt/betterdgg#19]
I think the way the light chat theme currently is clashes with the look of the rest of the site. I also think it could benefit from increasing the weight of the font in the chat window to make it less of an eye strain, but that may just be personal taste.

Here's an example of what it might look like if we implemented this: http://i.imgur.com/5So53tW.png?1

Again, this might all just be personal taste, but let me know and I can make the changes to the CSS, and I guess change the javascript to make it apply to the rest of the site.

**Comment by 9inevolt** [comment]
Closing this until someone is willing to working on it
